### ISSUE TITLE
question about the cal_dataset

### ISSUE THREAD

**Issue by tu2022** [microsoft/TransformerCompression#113]
hello, I want to prune a llama2 7b model which is pretrained with alpaca dataset and then finetuned with my own dataset. In this case, should i reset all the adapters, or can still use llama2 adapters. Besides, when i choose the cal_dataset for slicing the model, should i choose the alpaca dataset or my own dataset, which is not included in the finetuning dataset before.

looking forward to the reply.

**Comment by nailimixaM** [comment]
Hi, if I understand correctly you have a llama2 7b just with new weights - in that case you can use the llama2 adapter, and load the   weights from a local checkpoint using [`hf_utils.get_model_and_tokenizer`](https://github.com/microsoft/TransformerCompression/blob/65bcdb88254f0fb1cbc1f9069ea78732b9f985bf/src/slicegpt/hf_utils.py#L45).

As for the cal_dataset for slicing, you can use whatever dataset you prefer but it makes sense to slice with data which was used for finetuned. A mix of finetuned and pretraining data should work too!
