### ISSUE TITLE
Recovery the drop in accuracy

### ISSUE THREAD

**Issue by zhaoyang-star** [microsoft/TransformerCompression#119]
Researchers discovered that each transformer layer of LLMs impacts on accuracy differently. In general, the front layers are more important and should be pruned carefully. Besides, embedding and lm-head layers are also very important for keeping negligible accuracy drop. 

@nailimixaM So my question is:
- Will SliceGPT support skipping embedding and specific transformer layers? I guess it will achiveve better accuracy.
- How many effort is needed to implement it?

**Comment by nailimixaM** [comment]
Hi, we've got [slicing schedulers ](https://github.com/microsoft/TransformerCompression/blob/65bcdb88254f0fb1cbc1f9069ea78732b9f985bf/src/slicegpt/slicing_scheduler.py#L8 )for this, check them out. In the paper we tried out eigenvalue-based slicing scheduling, though didn't find it increase performance too much. If you find a slicing schedule that improves performance, let us know!

**Comment by zhaoyang-star** [comment]
> scheduling

Thanks for your quick feedback! 
Did you have do similar experiments that freezing input embedding and several top transformer layers while slicing other layers? [ShortGPT](https://arxiv.org/pdf/2403.03853.pdf) found that top layers are more important.
![image](https://github.com/microsoft/TransformerCompression/assets/24290792/cb5d377e-3cc9-4ae2-b8a2-6ec44a9de3bf)

**Comment by nailimixaM** [comment]
@zhaoyang-star in the paper we always performed constant slicing per layer, and achieved nice results - but there is definitely room for improvement by pruning some layers less than others!
