### ISSUE TITLE
How to load the tuned slicemodel

### ISSUE THREAD

**Issue by qxpBlog** [microsoft/TransformerCompression#140]
@mtodd @tpope @sverrejoh @radical @ijbaird After I finished fine-tuning, the content of the folder I obtained was exactly the same as the content of the file after slicing, so where is the weight of fine-tuning and how should I load the fine-tuning model.
![image](https://github.com/microsoft/TransformerCompression/assets/96739096/34c03426-86f4-4ce8-ae47-16a3fbd798d8)

**Comment by nailimixaM** [comment]
You can load the finetuned model in exactly the same way as you load the sliced model, see [this method](https://github.com/microsoft/TransformerCompression/blob/6b12cdee6ad51791d7c776b3a046bc408b9e77e9/src/slicegpt/hf_utils.py#L114)
