### ISSUE TITLE
A problem about the PPL value after sliced model fine-tuning

### ISSUE THREAD

**Issue by qxpBlog** [microsoft/TransformerCompression#141]
@nailimixaM @myshkov @mtodd @tpope @sverrejoh @radical Why does the PPL value increase after fine-tuning the sliced model:
![image](https://github.com/microsoft/TransformerCompression/assets/96739096/97e965d7-ba84-4ca4-92f8-c67de9f66293)

**Comment by EugeneLiu01** [comment]
The same thing happened to me. In my settings, the calibration dataset is different from fintuning dataset. The PPL value increased after finetuning the sliced model but zero-shot performance get improved.

**Comment by nailimixaM** [comment]
As @liuxiaozhu01 says, depends on your finetuning dataset. If you slice and finetune on non-test-splits of WikiText2 and evaluate the PPL on the test split you should see the PPL decrease.
