### ISSUE TITLE
PHI包导入问题

### ISSUE THREAD

**Issue by 1250826219** [microsoft/TransformerCompression#164]
#### Description
I encountered an ImportError when trying to import `Phi3Config` from `transformers.models.phi.modeling_phi`. It appears that `Phi3Config` does not exist in the current version of `transformers`.

#### Steps to Reproduce
```python
from transformers.models.phi.modeling_phi import Phi3Config
# Results in ImportError
我在使用linux远程主机时出现了这样的问题，但在本地服务器上并没有报错，可以帮帮我吗
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by 1250826219** [comment]
![Uploading Snipaste_2024-06-05_23-03-09.png…]()

**Comment by nailimixaM** [comment]
You'll need `transformers==4.41.0`. See [Phi3 files here in HF transformers repo](https://github.com/huggingface/transformers/tree/main/src/transformers/models/phi3).
