### ISSUE TITLE
parameter count is innacurate

### ISSUE THREAD

**Issue by jameshensman** [microsoft/TransformerCompression#72]
SliceGPT adds linear modules in the "skip connections" around each block. We currently implement these as pytorch buffers, which causes two problems:

1) counting the parameters is inaccurate (since buffers are not counted by default)
2) it's not straightforward to fine-tune these additional matrices (which may improve performance?)

Proposed solution:
change the buffers to actual linear layers, initialized as `torch.eye()`. At every place in the code where we check whether this buffer is `None`, we should replace that bit of code. During slicing, make sure to modify these buffers correctly. Update finetuning script (and BO script) to enable finetuning of these linears.

**Comment by nailimixaM** [comment]
Solved in #100.
